### PR TITLE
Remove unused resources

### PR DESCRIPTION
**Pull request by Jawnnypoo**
Hey, there were some unneeded things in the lib that could be removed, which would also mean that you could remove the support library dependency in the library, in case there is someone lucky out there who does not need the support lib. I also added a Travis CI script , which you can enable here
https://travis-ci.org/

### CODE REVIEW

**Comment by DmitryMalkovich** [comment]
Thank you! I will release a new version with your changes in one or two hour!

**Comment by Jawnnypoo** [comment]
Are you familiar with https://jitpack.io/ ? I think it would make it much easier for you to do releases. All you need to do is create a release in GitHub and it does the rest! :smile:

**Comment by DmitryMalkovich** [comment]
I am not familiar with https://jitpack.io/. I suppose that I selected the similar as far as I know https://bintray.com. To upload a new version you need to run a gradle script and confirm it via website of bintray. Seems it is more tricky than via jitpack). Thank you again for support! It is never late to switch to jitpack.io.

**Comment by Jawnnypoo** [comment]
No problem! For most of my library projects I have switched over to using it just because it is so much simpler to manage and perform releases. But bintray/jcenter is great too. :+1:

**Comment by DmitryMalkovich** [comment]
Nice coding!

**Comment by DmitryMalkovich** [comment]
Release v1.2:  https://github.com/DmitryMalkovich/material-design-dimens/releases/tag/1.2

**Pull request merged**
